### ISSUE TITLE
question

### ISSUE THREAD

**Issue by liuyang1273** [govindnh4cl/kaggle_blood_cells#1]
The line plot_learning_curves('100_0') failed at runtime: KeyError: '100_0_epoch'，why is that? @govindnh4cl

**Comment by 9autilus** [comment]
So `100_0_epoch` is the column in `stats.csv.py` that contains the epochs indices for the 100_0 experiment. Based on the information provided by your description, this error must have occurred toward the start (in terms of line number). Now, I can see that `stats.csv.py` does indeed [have a column](https://github.com/govindnh4cl/kagglebloodcells/blob/master/kaggle_blood_cells/stats.csv.py) named `100_0_epoch`. So most likely the `pandas.read_csv()` line didn't work for you correctly. Please confirm it.

If you're trying on Kaggle, then 'forking' the kernel does not install the GitHub packages with it. In my case, the `stats.csv.py` file is imported through a GitHub package following the instructions in [this kaggle kernel](https://www.kaggle.com/placidpanda/add-additional-input-files-in-your-kernels). That could be the reason why you would get the `KeyError`. However, you would have gotten some error with `pandas.read_csv()` as well. Do let me know if you still face the issue.
